# Autogenerated wrapper script for PROPOSAL_jll for aarch64-linux-gnu-cxx11
export libPROPOSAL

using CubicInterpolation_jll
using boost_jll
using spdlog_jll
JLLWrappers.@generate_wrapper_header("PROPOSAL")
JLLWrappers.@declare_library_product(libPROPOSAL, "libPROPOSAL.so")
function __init__()
    JLLWrappers.@generate_init_header(CubicInterpolation_jll, boost_jll, spdlog_jll)
    JLLWrappers.@init_library_product(
        libPROPOSAL,
        "lib/libPROPOSAL.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
